[package]
name = "rust-query-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = { version = "52.0.0", features = [
    "prettyprint",
] }
csv = "1.3.0"
serde = { version = "1.0.204", features = ["derive"] }
